name: Deploy Privacy Policy to GitHub Pages

on:
  push:
    branches:
      - main  # or change to your main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build HTML (optional if using raw .md or .html)
        run: |
          mkdir public
          cp edunova.md public/index.md

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

      - name: Deploy
        uses: actions/deploy-pages@v3
